spring.application.name=salao


spring.datasource.url=jdbc:postgresql://localhost:5432/leila_db
spring.datasource.username=usuario
spring.datasource.password=senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=leila-secret-dev-key-2024-muito-segura-aqui
jwt.expiration=86400000


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration